name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d
        with:
          python-version: "3.14"
          enable-cache: true

      - name: Set up Jake
        uses: AstraBert/setup-jake@v0.1.0

      - name: Run formatter
        shell: bash
        run: jake format

      - name: Run linter
        shell: bash
        run: jake lint

      - name: Run typecheck
        shell: bash
        run: jake ty

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Set up Jake
        uses: AstraBert/setup-jake@v0.1.0

      - name: Run Tests on Main Package
        run: jake test
